[TAIPY]

[DATA_NODE.input]
default_data = "21:int"

[DATA_NODE.intermediate]

[DATA_NODE.output]

[TASK.double]
function = "__main__.double:function"
inputs = [ "input:SECTION",]
outputs = [ "intermediate:SECTION",]
skippable = "False:bool"

[TASK.add]
function = "__main__.add:function"
inputs = [ "intermediate:SECTION",]
outputs = [ "output:SECTION",]
skippable = "False:bool"

[SCENARIO.my_scenario]
tasks = [ "double:SECTION", "add:SECTION",]
additional_data_nodes = []
name = "my_scenario"

[SCENARIO.my_scenario.comparators]

[SCENARIO.my_scenario.sequences]
